<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAqCdAey\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAqCdAey/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAqCdAey.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAqCdAey\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAqCdAey\App_KernelProdContainer([
    'container.build_hash' => 'AqCdAey',
    'container.build_id' => '9d63f163',
    'container.build_time' => 1593257281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAqCdAey');
