<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBBWvMl8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBBWvMl8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBBWvMl8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBBWvMl8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBBWvMl8\App_KernelDevDebugContainer([
    'container.build_hash' => 'BBWvMl8',
    'container.build_id' => 'c17f04cd',
    'container.build_time' => 1593626767,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBBWvMl8');
