<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR3t4G77\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR3t4G77/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR3t4G77.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR3t4G77\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR3t4G77\App_KernelDevDebugContainer([
    'container.build_hash' => 'R3t4G77',
    'container.build_id' => '5a30d4a8',
    'container.build_time' => 1593123834,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR3t4G77');
