<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_nom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_prenom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_mail', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_tel', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_mdp', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_confirm_mdp', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_adresse'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_nom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_prenom', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_mail', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_tel', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_mdp', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_confirm_mdp', '' . "\0" . 'App\\Entity\\Client' . "\0" . 'cli_adresse'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCliNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliNom', []);

        return parent::getCliNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliNom(string $cli_nom): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliNom', [$cli_nom]);

        return parent::setCliNom($cli_nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliPrenom', []);

        return parent::getCliPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliPrenom(string $cli_prenom): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliPrenom', [$cli_prenom]);

        return parent::setCliPrenom($cli_prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliMail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliMail', []);

        return parent::getCliMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliMail(string $cli_mail): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliMail', [$cli_mail]);

        return parent::setCliMail($cli_mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliTel', []);

        return parent::getCliTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliTel(?string $cli_tel): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliTel', [$cli_tel]);

        return parent::setCliTel($cli_tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliMdp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliMdp', []);

        return parent::getCliMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliMdp(string $cli_mdp): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliMdp', [$cli_mdp]);

        return parent::setCliMdp($cli_mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliAdresse(): ?\App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliAdresse', []);

        return parent::getCliAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliAdresse(\App\Entity\Address $cli_adresse): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliAdresse', [$cli_adresse]);

        return parent::setCliAdresse($cli_adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliConfirmMdp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliConfirmMdp', []);

        return parent::getCliConfirmMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliConfirmMdp(string $cli_confirm_mdp): \App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliConfirmMdp', [$cli_confirm_mdp]);

        return parent::setCliConfirmMdp($cli_confirm_mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

}
